# Generated by Django 4.2 on 2023-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicauth', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_present',
            field=models.BooleanField(default=False),
        ),
    ]
